a = float(input('Введите первое число ')) 
b = float(input('Введите второе число ')) 
с = (a+b) 
v = (a-b) 
d = (b-a) 
n = (a*b) 
l = (a/b) 
s = (b/a) 
x = (a**b) 
o = (b**a)
from math import *
m = sin(a)
g = sin(b)
z = cos(a)
k = cos(b)
f = str(a) + str(b)
p = str(b) + str(a)
print( a,'+',b,'=',с) 
print( a,'-',b,'=',v) 
print( b,'-',a,'=',d) 
print( a,'*',b,'=',n) 
print( a,'/',b,'=',l) 
print( b,'/',a,'=',s) 
print( a,'**',b,'=',x) 
print( b,'**',a,'=',o)
print(m)
print(g)
print(z)
print(k)
print(f)
print(p)
